name: studyo_music_library
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0  
  flame_audio: ^2.10.7
  shared_preferences: ^2.3.1
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/background/
    - assets/sounds/balance/
    - assets/sounds/bubble/
    - assets/sounds/clip/
    - assets/sounds/coins/
    - assets/sounds/deny/
    - assets/sounds/messages/
    - assets/sounds/pets_cleaning/
    - assets/sounds/pets_eat/
    - assets/sounds/pets_play/
    - assets/sounds/pickup/
    - assets/sounds/resources/
    - assets/sounds/review/
    - assets/sounds/success/
    - assets/sounds/tap/
    - assets/sounds/tetris/
    - assets/sounds/transitions/
    - assets/sounds/whoosh/
