name: studyo_music_library
description: "A comprehensive Flutter sound management library with BGM, SFX, and audio ducking capabilities."
publish_to: 'none'
version: 0.1.0
homepage: https://github.com/greek-cp/studyo_music_library
repository: https://github.com/greek-cp/studyo_music_library

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flame_audio: ^2.10.7
  shared_preferences: ^2.3.1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  get: ^4.7.2
  auto_size_text: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/background/
    - assets/sounds/balance/
    - assets/sounds/bgm/
    - assets/sounds/bubble/
    - assets/sounds/cheering/
    - assets/sounds/click/
    - assets/sounds/clip/
    - assets/sounds/coins/
    - assets/sounds/deny/
    - assets/sounds/fail/
    - assets/sounds/levelup/
    - assets/sounds/login/
    - assets/sounds/messages/
    - assets/sounds/notification/
    - assets/sounds/pets/
    - assets/sounds/pickup/
    - assets/sounds/reminders/
    - assets/sounds/resources/
    - assets/sounds/review/
    - assets/sounds/send/
    - assets/sounds/sfx/
    - assets/sounds/success/
    - assets/sounds/tap/
    - assets/sounds/tetris/
    - assets/sounds/transitions/
    - assets/sounds/whoosh/


export:
  flame_audio: ^2.10.7
